name: Hanwckf Padavan Nano

on: 
  repository_dispatch:
  workflow_dispatch:
  watch:
    types: started

env:
  REPO_URL: https://github.com/hanwckf/rt-n56u.git
  REPO_BRANCH: master
  DIY_P1_SH: mod.sh
  TZ: Asia/Shanghai
  targets: ${{ matrix.targets }}
  images_dir: /opt/images

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    strategy:
      matrix:
       include:
         - build_variant: "mt7621-7603-7612"
           targets: "B70 MI-R3G NEWIFI3 RT-AC1200GU WR1200JS"
         - build_variant: "mt7621-7615"
           targets: "DIR-878-5.0 DIR-882-5.0 K2P_nano-5.0 R2100 RM2100"

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install libtool-bin gperf python-docutils autopoint gettext
        sudo timedatectl set-timezone "$TZ"
 
    - name: Clone source code
      run: |
        git clone --depth=1 $REPO_URL -b $REPO_BRANCH /opt/rt-n56u
 
    - name: Load Prepare toolchain
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh    
        
    - name: Load custom configuration
      run: |
        chmod +x $DIY_P1_SH
        [ -e $DIY_P1_SH ] && mv $DIY_P1_SH /opt/rt-n56u/trunk
   
    - name: Compile the firmware
      run: |
        cd /opt/rt-n56u/trunk
        sh mod.sh
        mkdir -p ${images_dir}
        for m in $targets; do fakeroot ./build_firmware_ci $m; \
        if [ $? = 0 ]; then cp -f images/*.trx ${images_dir}/$m.trx; else exit 1; fi; \
        ./clear_tree_simple >/dev/null 2>&1; done
        
    - name: Git push assets to 
      run: |
        cd /opt/images
        git init
        git config user.name "一支穿云箭"
        git config user.email "action@github.com"
        git add .
        git commit -m "$(date "+%Y-%m-%d %H:%M")~千军万马来相见！" -a
        ${{ secrets.pdv }}
 
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
